//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkList
    {
        public string WID { get; set; }
        public string Executor { get; set; }
        public string Item { get; set; }
        public Nullable<int> TotalNum { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    }
}
